### ISSUE TITLE
Support OpenTelemetry

### ISSUE THREAD

**Issue by jackmpcollins** [jackmpcollins/magentic#136]
Each function created using a magentic decorator (`@prompt`, `@chatprompt`, etc.) should have a corresponding span, as if it was also decorated with [`@tracer.start_as_current_span()`](https://opentelemetry.io/docs/languages/python/instrumentation/#creating-spans-with-decorators). The function arguments (with strings truncated) should be set as attributes on the span. The function name and a hash of the template string/messages should also be set as attributes on the span so that filtering by a function or a specific prompt template is possible.

The template hash should be available to users as a `.template_hash` or similar method/property on their magentic functions so this is easily accessed. This should use `hashlib.sha256` to be stable across Python versions and reproducible outside of magentic.

Documentation for the opentelemetry integration should include instructions on how users should wrap the functions they pass to the `functions` argument. This is most useful for  `@prompt_chain` because it will make which function(s) the model decided to call visible in tracing. Maybe magentic should do this automatically?

Documentation for this should also include showing the traces in a UI, ideally one that can be easily installed and run locally. Looks like https://github.com/jaegertracing/jaeger is ideal.

Users should be able to configure whether magentic functions create spans, and whether/which function arguments are added as attributes to the spans.

**Comment by rawwerks** [comment]
Since "pydantic is all you need", maybe logfire is the way to go? 😉

**Comment by jackmpcollins** [comment]
OpenTelemetry supported now with release of https://github.com/jackmpcollins/magentic/releases/tag/v0.28.0 . See docs page https://magentic.dev/logging-and-tracing/

@patcher9 Thanks for discussing the implementation of this with me previously 🙏 I hope with the OTEL compatibility this will work with OpenLIT.
