### ISSUE TITLE
Support `tools` in LiteLLM chat model / upgrade from deprecated `functions` parameter.

### ISSUE THREAD

**Issue by mnicstruwig** [jackmpcollins/magentic#138]
I see that the [deprecated](https://litellm.vercel.app/docs/completion/function_call#deprecated---function-calling-with-completionfunctionsfunctions) `functions` parameter [is being used to pass in functions into the litellm completion function](https://github.com/jackmpcollins/magentic/blob/main/src/magentic/chat_model/litellm_chat_model.py#L240) in `magentic`.

Unfortunately this breaks support for certain models being use via `liteLLM`, specifically Mistral-Large, [which needs the new `tools` and `tool_choice` properties according to this comment](https://github.com/BerriAI/litellm/issues/2200#issuecomment-1969715754).

Is it at all possible to add support for `tools` to replace `functions` which is now deprecated?

**Comment by jackmpcollins** [comment]
I'm currently working on switching from functions to tools and planning to get those changes out this week. Just pushed the in-progress PR https://github.com/jackmpcollins/magentic/pull/144 which currently works for the OpenaiChatModel. The same changes can be made to the LitellmChatModel.

**Comment by mnicstruwig** [comment]
That's awesome @jackmpcollins thanks so much. Looking forward to the release, and really appreciate the quick feedback and updates!

**Comment by mschwaig** [comment]
I ran into the same error message you mentioned in https://github.com/jackmpcollins/magentic/issues/132 with Anthropic's API.

As far as I can tell that PR does not include working function calling / tool support yet, which should be resolved by https://github.com/jackmpcollins/magentic/pull/144.

**Comment by mnicstruwig** [comment]
@mschwaig That is correct!

**Comment by jackmpcollins** [comment]
@mnicstruwig  @mschwaig  I've published https://github.com/jackmpcollins/magentic/releases/tag/v0.18.0a0 which should allow using tools with the new Anthropic models via litellm. Please test it out and let me know how it goes!

**Comment by jackmpcollins** [comment]
@mnicstruwig @mschwaig  From my testing everything seems good, so I've released as https://github.com/jackmpcollins/magentic/releases/tag/v0.18.0  This allows using the new Claude models with function calling via litellm (see test [here](https://github.com/jackmpcollins/magentic/blob/395efa7af8e47865328e6400880ae70578b4b4db/tests/chat_model/test_litellm_chat_model.py#L29-L41)), and also adds the new `ParallelFunctionCall` and `AsyncParallelFunctionCall` types that allow you to use parallel function calling ([docs](https://magentic.dev/function-calling/)). Let me know if you run into any issues. Thanks

**Comment by mnicstruwig** [comment]
Thanks @jackmpcollins for the quick turnaround and amazing work!

I'll be able to test today (with Claude and Mistral), and let you know if I run into any problems.
