### ISSUE TITLE
allow tools to optionally terminate the execution of LLM-powered functions

### ISSUE THREAD

**Issue by mschwaig** [jackmpcollins/magentic#145]
I have a project where I would like an LLM to iteratively improve a code snippet with the help of various tools.
One of those tools invokes a interpreter with the updated code that the LLM came up with, as often as required.

Once the interpreter invocation succeeds without error, there is no reason to return to the LLM-powerd function again, instead the LLM-powered function could simply return as well.

As far as I could tell from the docs it is currently not possible for user-written tools to do this.

The following comment makes me think something like this might be possible, since tool invocation is already used to terminate the execution of LLM-powered functions:

> magentic uses function calling / tool calls to return most of these objects. `list[int]` gets converted into a function called "return_list_int" that GPT can choose to use, and if chosen the response gets parsed into a `list[int]` by magentic.
>
> _Originally posted by @jackmpcollins in https://github.com/jackmpcollins/magentic/pull/144#discussion_r1520392721_

**Comment by mschwaig** [comment]
Thanks for the suggestion. I had to think about it, but now it makes sense to me.
My code is quite similar, so you got the idea right.

The main differences being that I was using `@prompt_chain` and did not have `FunctionCall` as one of the return parameters.

```
@prompt_chain("""
    Modify the following code until it runs without error:
    ```
    {code}
    ```
     """
    functions=[run_code_and_get_feedback]
)
def llm(code:str) -> str: ...

code = # some sensible code snippet
working_code = llm(code)
```

I think there were two flaws with how I was trying to do this.

#### Flaw 1

Eventually I realized that function calling in current LLMs seems to be much more primitive than I expected, and they are probably trained not to invoke `run_code_and_get_feedback` more than once (see also https://community.openai.com/t/function-calls-multiple-function-calls-to-same-function/348937). Though I was only able to actually test this with the OpenAI API so far.

#### Flaw 2

The reasons I wanted to use `@prompt_chain` and invoke `run_code_and_get_feedback` over and over again were
1. that I thought this way the LLM get to see the initial prompt as well as all of the previous  `run_code_and_get_feedback`  invocations and the returned errors in the same context.
2. I also thought that this would be more efficient, since the context for the ongoing `llm` invocation could be updated with the output of from `run_code_and_get_feedback` before proceeding to generate output.

It would be really great if you could clarify the following:

Is my assumption right that the 'scope' of the LLMs context is the current invocation of the decorated function?
If yes, does making this work with `@prompt_chain` imply magentic stitching together the context from the prompt and all of the interleaved LLM responses and results from tool invocations and passing that as the next input to the LLM, or can that process happen more efficiently (in terms of tokens)?

**Comment by jackmpcollins** [comment]
Thanks @mnicstruwig for answering here.

@mschwaig to answer your questions

> Is my assumption right that the 'scope' of the LLMs context is the current invocation of the decorated function?

For `@prompt` and `@chatprompt` when the function is called only the message(s) that are in the decorator will be passed to the LLM and only one query will be made to the LLM. A way to think of these is that they only add a single "assistant" message to the chat.

`@prompt_chain` makes a call to the LLM and if the response is a `FunctionCall` (for a function in the `functions` argument) then `prompt_chain` automatically calls that, appends the result to the chat, and makes another call to the LLM. This continues until the LLM returns something that is not a `FunctionCall`, which is returned as the final result.

You are correct that in both cases the "chat" with the LLM exists only during the decorated function's invocation.

> If yes, does making this work with @prompt_chain imply magentic stitching together the context from the prompt and all of the interleaved LLM responses and results from tool invocations and passing that as the next input to the LLM, or can that process happen more efficiently (in terms of tokens)?

The `@prompt_chain` decorator is just continuing the chat conversation by adding the function call results. To summarize the chat history or exclude certain messages you would have to do something custom. There is [the `Chat` class](https://github.com/jackmpcollins/magentic/blob/3dc29632f993a95f416adfcda522dcc238de4214/src/magentic/chat.py#L19) in magentic which is used internally by `prompt_chain` and would help with this - I haven't documented it yet and might change the API slightly. You can see how it's used in `@prompt_chain` [here](https://github.com/jackmpcollins/magentic/blob/3dc29632f993a95f416adfcda522dcc238de4214/src/magentic/prompt_chain.py#L74-L85).

Another idea that might work for your use case is to have two prompt-functions, one for `code + error -> updated code` and one for `code -> testing_function`. You could then control the loop in python. This would mean the previous errors/fixes are not visible to model but there is no cumulative context. Something like

```python

from enum import Enum

class TestType(Enum):  # Enums to codify categorical options
    INTERPRETER = "interpreter"
    LINTER = "linter


@prompt(
    """How should this code be tested?

    {code}
    """
def choose_test -> TestType: ...

@prompt(
    """Update the following code based on the error.
    Error: {error}
    
    {code}
    """
def update_code(code: str, error: str) -> str: ...


code = "<initial code>"
for _ in range(10):  # Could while loop until code doesn't change?
    test_type = choose_test(code)
    test = get_test_for_test_type(test_type)
    test_result = test(code)
    code = update_code(code, test_result)
```

---

`@prompt_chain` should work for this use case. Here's some imperfect but mostly-working code to demonstrate. I found that the model likes to jump straight to the solution, so more prompt-engineering is probably required.


```python
from magentic import prompt_chain, OpenaiChatModel


def submit_code_for_evaluation(description_of_changes: str, lines_of_code: list[str]) -> str:
    code = "\n".join(lines_of_code)  # Avoids JSON serialization issues with newlines

    print("\n---\n")
    print("Running code")
    print("Changes:", description_of_changes)
    print()
    print(code)
    try:
        exec(code)  # DANGER: Be careful what code you let this execute
        print("Result: Success")
        return "Success"
    except Exception as e:
        print(f"Error: {e}")
        return f"Error: {e}"


@prompt_chain("""
    Modify the following code until it runs without error.
    Use the available tools to test the code after each modification.
    First test the initial code before making any changes.
    Then make a small change to correct the error and test again.
    Before returning the final code, test it to make sure it works.
    Do not describe the error or changes between attempts.
    When it is working, return just the code with no extra text.
    ```
    {code}
    ```
    """,
    functions=[submit_code_for_evaluation],
    model=OpenaiChatModel("gpt-4"),
)
def llm(code: str) -> str: ...


code = """
def fib(n):
    '''Return the nth number in the Fibonacci sequence'''
   raise NotImplementedError

assert fib(5) == 5
assert fib(7) == 55
"""
working_code = llm(code)
```

<details>
<summary>Printed output</summary>

```

---

Running code
Changes: Initial test before making any changes.

def fib(n):
    '''Return the nth number in the Fibonacci sequence'''
   raise NotImplementedError

assert fib(5) == 5
assert fib(10) == 55
Error: unindent does not match any outer indentation level (<string>, line 3)

---

Running code
Changes: Fixing the indentation error in the raise statement.

def fib(n):
    '''Return the nth number in the Fibonacci sequence'''
    raise NotImplementedError

assert fib(5) == 5
assert fib(10) == 55
Error: 

---

Running code
Changes: Implementing the fib function.

def fib(n):
    '''Return the nth number in the Fibonacci sequence'''
    if n <= 1:
       return n
    elif n == 2:
       return 1
    else:
       a, b = 0, 1
       for _ in range(n - 1):
           a, b = b, a + b
       return b

assert fib(5) == 5
assert fib(10) == 55
Result: Success
```

</details>

<details>
<summary>Returned output</summary>

````
```
def fib(n):
    '''Return the nth number in the Fibonacci sequence'''
    if n <= 1:
       return n
    elif n == 2:
       return 1
    else:
       a, b = 0, 1
       for _ in range(n - 1):
           a, b = b, a + b
       return b

assert fib(5) == 5
assert fib(10) == 55
```
````

</details>

**Comment by jackmpcollins** [comment]
@mschwaig  I'm going to close this issue. Please reopen or create a new issue if the above answers don't resolve this. Thanks
