### ISSUE TITLE
Question: Can I use Ollama for function calling through magentic

### ISSUE THREAD

**Issue by DevAseel** [jackmpcollins/magentic#199]
Hey folks!

First, would like to express my appreciation for maintaining and developing this cool tool!

I have a quick question when using function calling through Ollama, does it currently support function calling? I'm using mistral model. 

Thank you!

**Comment by jackmpcollins** [comment]
Hi @DevAseel , thanks for the kind words! There's an open issue here for using structured outputs and function calls with ollama https://github.com/jackmpcollins/magentic/issues/194  so please follow that.

**Comment by jackmpcollins** [comment]
Resolution from the other issue: https://github.com/jackmpcollins/magentic/issues/194#issuecomment-2097471824

**Comment by jackmpcollins** [comment]
See also: https://github.com/jackmpcollins/magentic/issues/207#issuecomment-2507359293
