### ISSUE TITLE
`magentic` doesn't allow manual error handling when input arguments don't match tool schema

### ISSUE THREAD

**Issue by mnicstruwig** [jackmpcollins/magentic#211]
Hi @jackmpcollins !

I'm attempting to implement error handling for function calling, specifically in the case where the LLM provides inputs that do not match the required input schema. Here is an example where I force an incorrect function call:

```python
from magentic import (
    chatprompt,
    prompt,
    ParallelFunctionCall,
    FunctionResultMessage,
    AssistantMessage,
    UserMessage,
    SystemMessage,
    FunctionCall,
)
from openbb import obb
from pydantic import Field, ValidationError
from typing import Literal

def get_profit(symbols, period: Literal["quarter", "annual"]) -> str:
    if period not in ["quarter", "annual"]:
        raise ValidationError(
            f"Invalid period: {period}. Expected 'quarter' or 'annual'."
        )
    return "25%"

messages = []
messages.append(
    SystemMessage("What is the profit margin of TSLA, AMZN, MSFT, AAPL, RDDT?")
)

function_call = FunctionCall(
    function=get_profit,
    **{
        "symbols": "TSLA,AMZN,MSFT,AAPL,RDDT",
        "period": 1,
    },  # <-- "period" is an invalid input
)

messages.append(AssistantMessage(function_call))
messages.append(
    FunctionResultMessage(content="Something went wrong.", function_call=function_call)
)

@chatprompt(*messages, functions=[get_profit])
def _llm() -> str | ParallelFunctionCall:
    ...

r = _llm()
```

This raises the following error:
```python
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[52], line 30
     22 @chatprompt(
     23     *messages,
     24     functions=[get_profit]
     25 )
     26 def _llm() -> str | ParallelFunctionCall:
     27     ...
---> 30 r = _llm()

File ~/miniforge3/envs/obb-agents/lib/python3.11/site-packages/magentic/chatprompt.py:88, in ChatPromptFunction.__call__(self, *args, **kwargs)
     86 def __call__(self, *args: P.args, **kwargs: P.kwargs) -> R:
     87     """Query the LLM with the formatted chat prompt template."""
---> 88     message = self.model.complete(
     89         messages=self.format(*args, **kwargs),
     90         functions=self._functions,
     91         output_types=self._return_types,
     92         stop=self._stop,
     93     )
     94     return message.content

File ~/miniforge3/envs/obb-agents/lib/python3.11/site-packages/magentic/chat_model/openai_chat_model.py:456, in OpenaiChatModel.complete(self, messages, functions, output_types, stop)
    448 streamed_str_in_output_types = is_any_origin_subclass(output_types, StreamedStr)
    449 allow_string_output = str_in_output_types or streamed_str_in_output_types
    451 response: Iterator[ChatCompletionChunk] = discard_none_arguments(
    452     self._client.chat.completions.create
    453 )(
    454     model=self.model,
    455     messages=_add_missing_tool_calls_responses(
--> 456         [message_to_openai_message(m) for m in messages]
    457     ),
    458     max_tokens=self.max_tokens,
    459     seed=self.seed,
    460     stop=stop,
    461     stream=True,
    462     temperature=self.temperature,
    463     tools=[schema.to_dict() for schema in tool_schemas] or openai.NOT_GIVEN,
    464     tool_choice=self._get_tool_choice(
    465         tool_schemas=tool_schemas, allow_string_output=allow_string_output
    466     ),
    467 )
    469 first_chunk = next(response)
    470 # Azure OpenAI sends a chunk with empty choices first

File ~/miniforge3/envs/obb-agents/lib/python3.11/site-packages/magentic/chat_model/openai_chat_model.py:456, in <listcomp>(.0)
    448 streamed_str_in_output_types = is_any_origin_subclass(output_types, StreamedStr)
    449 allow_string_output = str_in_output_types or streamed_str_in_output_types
    451 response: Iterator[ChatCompletionChunk] = discard_none_arguments(
    452     self._client.chat.completions.create
    453 )(
    454     model=self.model,
    455     messages=_add_missing_tool_calls_responses(
--> 456         [message_to_openai_message(m) for m in messages]
    457     ),
    458     max_tokens=self.max_tokens,
    459     seed=self.seed,
    460     stop=stop,
    461     stream=True,
    462     temperature=self.temperature,
    463     tools=[schema.to_dict() for schema in tool_schemas] or openai.NOT_GIVEN,
    464     tool_choice=self._get_tool_choice(
    465         tool_schemas=tool_schemas, allow_string_output=allow_string_output
    466     ),
    467 )
    469 first_chunk = next(response)
    470 # Azure OpenAI sends a chunk with empty choices first

File ~/miniforge3/envs/obb-agents/lib/python3.11/functools.py:909, in singledispatch.<locals>.wrapper(*args, **kw)
    905 if not args:
    906     raise TypeError(f'{funcname} requires at least '
    907                     '1 positional argument')
--> 909 return dispatch(args[0].__class__)(*args, **kw)

File ~/miniforge3/envs/obb-agents/lib/python3.11/site-packages/magentic/chat_model/openai_chat_model.py:96, in _(message)
     85 if isinstance(message.content, FunctionCall):
     86     function_schema = FunctionCallFunctionSchema(message.content.function)
     87     return {
     88         "role": OpenaiMessageRole.ASSISTANT.value,
     89         "content": None,
     90         "tool_calls": [
     91             {
     92                 "id": message.content._unique_id,
     93                 "type": "function",
     94                 "function": {
     95                     "name": function_schema.name,
---> 96                     "arguments": function_schema.serialize_args(message.content),
     97                 },
     98             }
     99         ],
    100     }
    102 if isinstance(message.content, ParallelFunctionCall):
    103     return {
    104         "role": OpenaiMessageRole.ASSISTANT.value,
    105         "content": None,
   (...)
    118         ],
    119     }

File ~/miniforge3/envs/obb-agents/lib/python3.11/site-packages/magentic/chat_model/function_schema.py:408, in FunctionCallFunctionSchema.serialize_args(self, value)
    407 def serialize_args(self, value: FunctionCall[T]) -> str:
--> 408     return self._model(**value.arguments).model_dump_json(exclude_unset=True)

File ~/miniforge3/envs/obb-agents/lib/python3.11/site-packages/pydantic/main.py:176, in BaseModel.__init__(self, **data)
    174 # `__tracebackhide__` tells pytest and some other tools to omit this function from tracebacks
    175 __tracebackhide__ = True
--> 176 self.__pydantic_validator__.validate_python(data, self_instance=self)

ValidationError: 1 validation error for FuncModel
period
  Input should be 'quarter' or 'annual' [type=literal_error, input_value=1, input_type=int]
    For further information visit https://errors.pydantic.dev/2.7/v/literal_error
```

It looks like `magentic` is still trying to enforce input argument schemas, even if they're handled and occur outside of `magentic`. 

This makes it impossible to error-handle cases where the LLM hallucinates and provides inputs that do not pass validation for the function schema model that is created from the provided tools (which are a common failure mode of LLMs).

Should I be taking a different approach?

Thanks!

**Comment by mnicstruwig** [comment]
For those who stumble upon this in the meantime, this works as a simple workaround:

Create a new dummy function that can accept any args / kwargs, and then modify its name to match that of the original called function in the bad function call. The new permissive signature will sidestep the pydantic model validation in `magentic`, and still allow you to inform the LLM that something went wrong so that it can (hopefully) self-heal its next input.

```python
                    dummy = lambda *args, **kwargs: ...
                    dummy.__name__ = function_call.function.__name__
                    new_function_call = FunctionCall(
                        function=dummy,
                        **function_call.arguments,
                    )
                    messages.append(AssistantMessage(new_function_call))
                    messages.append(
                        FunctionResultMessage(
                            content=str(error_message), function_call=new_function_call
                        )
                    )
```

**Comment by jackmpcollins** [comment]
I can reproduce this with 

```python
import logging
from typing import Literal

from magentic import prompt, FunctionCall

logging.basicConfig(level=logging.DEBUG)


def func(a: Literal[1, 2]) -> str:
    return f"Received {a}"


@prompt(
    "Call the function with input 3",
    functions=[func],
)
def test() -> FunctionCall: ...


test()
```

The root cause is that pydantic is being used internally to deserialize the function arguments to match the signature types. I think raising an error when the LLM fails to match the types is good default behavior because it means the function can expect valid inputs (as would be the case if it were called normally in a type-checked codebase).

Thankfully, pydantic has tools for customizing the validation. One option in this case is the `SkipValidation` annotation. https://docs.pydantic.dev/latest/api/functional_validators/#pydantic.functional_validators.SkipValidation

```python
from typing import Literal

from pydantic import SkipValidation
from magentic import prompt, FunctionCall


def func(a: SkipValidation[Literal[1, 2]]) -> str:
    return f"Received {a}"


@prompt(
    "Call the function with input 3",
    functions=[func],
)
def test() -> FunctionCall: ...


test()
# FunctionCall(<function func at 0x105bc6440>, 3)
```

More advanced coercion can be done using their more general validators https://docs.pydantic.dev/latest/concepts/validators/#annotated-validators

---

Separately, another/additional approach would be to add a description for this input so hopefully the model gets it correct more often. The example results in an error roughly half the time.

```python
from typing import Annotated, Literal

from pydantic import Field
from magentic import prompt, FunctionCall


def func(
	a: Annotated[Literal[1, 2], Field(description="Only 1 or 2 are allowed!!")],
) -> str:
    return f"Received {a}"


@prompt(
    "Call the function with input 3 unless otherwise specified.",
    functions=[func],
)
def test() -> FunctionCall: ...


test()
```

**Comment by mnicstruwig** [comment]
Hi @jackmpcollins, thanks for the quick reply!

> I think raising an error when the LLM fails to match the types is good default behavior because it means the function can expect valid inputs (as would be the case if it were called normally in a type-checked codebase).

I 100% agree with you that this should be default behaviour. My example is specifically about an edge-case where I'm trying to error-handle the scenario where the model doesn't follow the function's input schema. My intended flow was:

- Run LLM completion
- Capture the function call
- Manually execute the function in a `try...except` to catch any error
- If there's an error, pass the error to the LLM in an attempt to self-heal
- Run another loop.

This flow works for all kinds of exceptions _except_ those that validate the input schema. This case occurs often enough in my use-case that it does need to be error-handled (I'm passing in up to four [OpenBB Platform](https://github.com/OpenBB-finance/OpenBBTerminal/tree/develop/openbb_platform) functions in, which can sometimes have quite a few arguments -- albeit many of them default) which trips up the model occasionally. All of the functions have good type annotations and descriptions (I'm working with them to make things as `magentic`-compatible as possible).

I didn't know about `SkipValidation`! However, the problem with the `SkipValidation` approach is that I'm trying to use external functions as tools with `magentic` rather than ones I've defined myself.

> Separately, another/additional approach would be to add a description for this input so hopefully the model gets it correct more often. 

This is something that would be difficult to do with external libraries. But it's a good idea to be explicit in the _description_ itself what possible values are.

In the meantime though, I guess it's the lambda approach for now to error-handle this scenario?

**Comment by jackmpcollins** [comment]
Ah, I misunderstood initially. The issue was in just the serialization of the `FunctionResultMessage` that had "invalid" inputs. Validation of the function arguments on serialization is not necessary because the `FunctionCall` was either created by
- the LLM, so already passed the validation on being parsed
- or the user, in which case we should trust their decision

I've fixed this now in https://github.com/jackmpcollins/magentic/releases/tag/v0.24.0  The code you provided in the description now runs without error for me. let me know if you run into any issues with this, thanks.

**Comment by mnicstruwig** [comment]
Super, thanks!
