### ISSUE TITLE
Allow custom_llm_parameter with LiteLLM backend

### ISSUE THREAD

**Issue by entropi** [jackmpcollins/magentic#222]
LiteLLM supports an optional `custom_llm_provider` parameter which we make use of. 

[This PR](https://github.com/jackmpcollins/magentic/pull/221) adds support for passing it through.

**Comment by jackmpcollins** [comment]
Thanks for the PR! Released now in https://github.com/jackmpcollins/magentic/releases/tag/v0.25.0

**Comment by entropi** [comment]
Thanks!
