### ISSUE TITLE
Feature Request/Idea: implement Semantic Layer

### ISSUE THREAD

**Issue by qdrddr** [jackmpcollins/magentic#248]
Semantic Layer helps to automatically select context saved into vector database based on user prompt and are more suitable for individual functions guardrailing LLM to better work with the function.

**Comment by jackmpcollins** [comment]
Hi @qdrddr could you give some pseudocode or a description of a use case to illustrate what this would do and how you would use it? Thanks

**Comment by jackmpcollins** [comment]
Closing this to tidy issues, but feel free to reopen.
