### ISSUE TITLE
Do not pass stream_options param to AzureOpenai

### ISSUE THREAD

**Issue by jackmpcollins** [jackmpcollins/magentic#261]
According to usage in https://github.com/borh/hachidaishu-translation , `AzureOpenAI` does yet support `stream_options` which is used to request usage info from OpenAI. For the moment this should be left unset when using the `AzureOpenAI` client.

https://github.com/borh/hachidaishu-translation/blob/d1fc5e51365f3a10a4e90d906f00a7070e4e1002/src/hachidaishu_translation/gen.py#L202-L203

Related issues
- https://github.com/Azure/azure-rest-api-specs/issues/29157
- https://github.com/openai/openai-python/issues/1469

cc @borh

**Comment by jackmpcollins** [comment]
✨✨ Here's [an AI-assisted sketch of how you might approach this issue](https://copilot-workspace.githubnext.com/jackmpcollins/magentic/issues/261?shareId=18efd890-04fc-4ebb-8b32-fb14e086c294) saved by @jackmpcollins using Copilot Workspace v0.22

<details open><summary><b>Topic</b></summary>
<br/>

Does the AzureOpenAI client omit the stream_options parameter?

</details>

<details open><summary><b>Before</b></summary>
<br/>

* No, the `AzureOpenAI` client does not omit the `stream_options` parameter.
* In `src/magentic/chat_model/openai_chat_model.py`, the `OpenaiChatModel` class includes a `_get_stream_options` method that returns `{"include_usage": True}`.
* The `OpenaiChatModel` constructor initializes the client as `openai.AzureOpenAI` when `api_type` is "azure".
* The `complete` and `acomplete` methods in `OpenaiChatModel` use `_get_stream_options` in their parameters.
* The `stream_options` parameter is passed to the Azure client, which does not support it, causing issues.


</details>
<details open><summary><b>After</b></summary>
<br/>

- Yes, the `AzureOpenAI` client now omits the `stream_options` parameter.
- In `src/magentic/chat_model/openai_chat_model.py`, the `OpenaiChatModel` class `_get_stream_options` method returns `openai.NOT_GIVEN` when `api_type` is "azure".
- The `_get_stream_options` should now be an instance method instead of a staticmethod, and use `self.api_type`
- The `complete` and `acomplete` methods in `OpenaiChatModel` use `_get_stream_options` in their parameters, which now correctly omits `stream_options` for Azure.

</details>

<details open><summary><b>Plan</b></summary>
<br/>

* `src/magentic/chat_model/openai_chat_model.py` (CHANGE)
  - Update `_get_stream_options` method to return `openai.NOT_GIVEN` when `self.api_type` is "azure"
  - Change `_get_stream_options` method to be an instance method instead of a staticmethod
* `tests/chat_model/test_openai_chat_model.py` (CHANGE)
  - Add a test to verify that `AzureOpenAI` client omits the `stream_options` parameter

</details>

<details open><summary><b>Sketch of implementation</b></summary>
<br/>

[View the changes](https://copilot-workspace.githubnext.com/jackmpcollins/magentic/issues/261?shareId=18efd890-04fc-4ebb-8b32-fb14e086c294)

<details open><summary><b>Details</b></summary>
<br/>

Code analyzed at f0c2fce9cebc26dcc6d22d87f8b286abdb4e10fd

</details>

**Comment by borh** [comment]
Thanks! I tried your PR against my code without the workaround and it worked.

**Comment by jackmpcollins** [comment]
@borh Thanks for testing! I haven't been using Azure myself so if you find any more bugs or improvements please file an issue or PR.

I've made an issue to add tests against Azure. It might even be worth making a separate `AzureChatModel` if there's enough difference with the `OpenaiChatModel`.

**Comment by jackmpcollins** [comment]
@borh  The fix is released now in https://github.com/jackmpcollins/magentic/releases/tag/v0.28.0 Please let me know how that works for you
