### ISSUE TITLE
Mistral function calling uses invalid `tool_id` length

### ISSUE THREAD

**Issue by mnicstruwig** [jackmpcollins/magentic#276]
Hi @jackmpcollins!

I've been experimenting with Mistral's models again, and I've noticed that function calling is broken when using `chatprompt` to manually execute function calls while using the `MistralChatModel`:

```
openai.BadRequestError: Error code: 400 - {'object': 'error', 'message': 'Tool call id was 38f04d9ea185424a8dc6ed9a88da5 but must be a-z, A-Z, 0-9, with a length of 9.', 'type': 'invalid_request_error', 'param': None, 'code': None}
```

It looks like, for Mistral, tool call ids must be a length of 9.

I can confirm that things work if I change the [unique tool call id generation](https://github.com/jackmpcollins/magentic/blob/main/src/magentic/function_call.py#L27) to be a length of 9.

Any ideas on what's the best way of addressing this so that we change the length when we're using `MistralChatModel`?

**Comment by jackmpcollins** [comment]
I think updating the id generation to chop at 9 chars instead of 29 would be fine. Hopefully the LLM providers never put mutually exclusive constraints on this id!
https://github.com/jackmpcollins/magentic/blob/5a51fbb32b87041b9f810f952e9541860253d256/src/magentic/function_call.py#L27-L29

**Comment by jackmpcollins** [comment]
@mnicstruwig Released now in https://github.com/jackmpcollins/magentic/releases/tag/v0.28.1
