### ISSUE TITLE
Support setting system prompt

### ISSUE THREAD

**Issue by jackmpcollins** [jackmpcollins/magentic#31]
Support setting the system message.

```python
from magentic import prompt


@prompt(
    'Add more "dude"ness to: {phrase}',
    system="You are the coolest dude ever.",
)
def dudeify(phrase: str) -> str:
    ...
```

- `system` should support templating in the same way that `template` does.
- (future) `prompt` should output a warning that `system` is being ignored when it is passed in combination with a completions model (if/when support for those is added).

**Comment by bitsnaps** [comment]
I wouldn't fire a new issue for this error:
```
ValueError: String was returned by model but not expected. You may need to update your prompt to encourage the model to return a specific type.
```
at this line:
```python
verification_questions = await generate_verification_questions(query, baseline_response)
```
is this issue related to that one?
P.S. Here is the output of the previous Notebook cell:
```
Sure, here are a few politicians born in New York, New York:
1. Hillary Clinton
2. Donald Trump
3. Franklin D. Roosevelt
4. Rudy Giuliani
5. Theodore Roosevelt
```

**Comment by jackmpcollins** [comment]
@bitsnaps I've created an issue for this here https://github.com/jackmpcollins/magentic/issues/33

**Comment by jackmpcollins** [comment]
This is now possible using `@chatprompt` in https://github.com/jackmpcollins/magentic/releases/tag/v0.7.0

cc @yudataguy
