### ISSUE TITLE
How to switch models, other than redefining the function?

### ISSUE THREAD

**Issue by benwhalley** [jackmpcollins/magentic#311]
Perhaps I'm not understanding, but it seems like there's no way to switch which model is being used, other than to redefine the function with a different decorator?

Is that correct? If so, would it be possible to include a mechanism to pass the model to the function at runtime, so that you could do:

```

gpt4 = LitellmChatModel('gpt-4o')
llama3 = LitellmChatModel("ollama/llama3.1")


@magentic.prompt("tell me a joke about {thing}", model=gpt4)
def joke(thing: str) -> str: ...  


joke("apples")
joke("apples", model=llama3)


```

and this would call the different models?

**Comment by benwhalley** [comment]
as an aside, but relatedly, it's somewhat annoying to only be able to change the default model by setting an ENV var. It would be nice if this could be done programatically too.

**Comment by CiANSfi** [comment]
Would using two functions, one for each model, suit you @benwhalley ? See here in the last code example: https://magentic.dev/configuration/

**Comment by benwhalley** [comment]
I can see that you could do that, but it just seems like the model you use shouldn't be tied to the function itself. Likewise for things like temperature etc.

In the work I'm doing now I'd like to be able to compare models, settings etc so it would take some metaprogramming to be able to define functions on the fly, which isn't ideal (and I really like elements of magentic)

**Comment by benwhalley** [comment]
hi - yes, this makes sense and I can see it's a tradeoff to avoid having to pass the model down the chain. The context managers work for setting both the model and retry model btw.

**Comment by jackmpcollins** [comment]
Great! Closing this issue. Separate issue for setting default model is https://github.com/jackmpcollins/magentic/issues/313
