### ISSUE TITLE
Placeholder for an arbitrary list of messages in the @chatprompt (for chat history)

### ISSUE THREAD

**Issue by gabayben** [jackmpcollins/magentic#340]
Currently, you are only able to hard code messages in @chatprompt

For example:

```
@chatprompt(
    SystemMessage(...),
    UserMessage(...),
    AssistantMessage(...)
)
def some_prompt(key: str) -> str: ...

some_prompt.format({'key': 'value'})
# [SystemMessage, UserMessage, AssistantMessage]
```

There should be a kind of placeholder for a list of messages that will be included in the formatted list of messages that are returned from the format method. This could be  used to include chat history.

For example, suppose this placeholder is called ChatPlaceholder:

```
@chatprompt(
    SystemMessage(...),
    UserMessage(...),
    ChatPlaceholder(name='chat_history')
)
def some_prompt(key: str, chat_history: list[Message]) -> str: ...

chat_history = [UserMessage(...), AssistantMessage(...), ToolMessage(...)]
some_prompt.format({'key': 'value', 'chat_history': chat_history})
# [SystemMessage, UserMessage, UserMessage, AssistantMessage, ToolMessage]
```

Let me know what you think, and if you need any clarification.

**Comment by jackmpcollins** [comment]
@gabayben  I think the `Chat` class (currently undocumented, issue #317 ) might be a neater way to achieve something like this, as it avoids prompt-function parameters becoming a mix of message contents and messages.

https://github.com/jackmpcollins/magentic/blob/5986060c2e9c52736bb5017dfe4e20f5cbde6eff/src/magentic/chat.py#L25-L36

So your function above would become something like

```python
def some_prompt(key: str, chat_history: list[Message]) -> str: ...
	chat = Chat(
		[
			SystemMessage(...),
		    UserMessage(...),
			*chat_history,
		]
		output_types=[str]
	)
	return chat.submit().last_message.content
```

Let me know what you think and if this works for what you need. Thanks

**Comment by gabayben** [comment]
Oh I see. I didn't know about Chat. This looks like a better way to achieve this. Thanks!
