### ISSUE TITLE
logfire not logging the response

### ISSUE THREAD

**Issue by rawwerks** [jackmpcollins/magentic#359]
i'm following along with https://magentic.dev/logging-and-tracing/ , but i don't think `logfire.instrument_openai()` is fully implemented correctly, because i cannot see the response in logfire. 

example: 
```
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

import logfire

logfire.configure()
logfire.instrument_openai()  # optional, to trace OpenAI API calls  
logfire.info('Hello, {name}!', name='world')

from magentic import prompt
from pydantic import BaseModel


class Superhero(BaseModel):
    name: str
    age: int
    power: str
    enemies: list[str]


@prompt("Create a Superhero named {name}.")
def create_superhero(name: str) -> Superhero: ...


create_superhero("Monkey Boy")
```

result:
![CleanShot 2024-10-22 at 07 27 34@2x](https://github.com/user-attachments/assets/6879c9c6-7ce8-48d0-b549-4536142962cf)

**Comment by jackmpcollins** [comment]
You're right! This works for non-streamed responses, but not when `stream=True`. I've opened an issue with logfire now https://github.com/pydantic/logfire/issues/542

**Comment by jackmpcollins** [comment]
@rawwerks Logfire PR is here if you'd like to test it out https://github.com/pydantic/logfire/pull/545

<img width="379" alt="image" src="https://github.com/user-attachments/assets/9647588c-68cb-4441-a971-1360e82d9944">

**Comment by jackmpcollins** [comment]
@rawwerks  This fix was released in https://github.com/pydantic/logfire/releases/tag/v2.2.0 🎉
