### ISSUE TITLE
Integrate with Llamaindex

### ISSUE THREAD

**Issue by smyja** [jackmpcollins/magentic#41]
Would be nice to integrate this with llamaindex.

**Comment by jackmpcollins** [comment]
@smyja Could you share some details or examples of how this would work and what it would allow you to do. Thanks

**Comment by smyja** [comment]
> @smyja Could you share some details or examples of how this would work and what it would allow you to do. Thanks

We could index pdf stories to create new stories or plays based on the characters in the book, also would be able to use other llms and numerous data sources since llamaindex supports multiple. 

Here's a section on structured output that I feel magnetic could be added.  https://gpt-index.readthedocs.io/en/stable/core_modules/query_modules/structured_outputs/root.html

**Comment by jackmpcollins** [comment]
I'm planning to keep magentic separate to llamaindex for the moment / no code integration. I would be happy to accept a PR adding an example notebook showing end-to-end how magentic and llamaindex can be used together to do something that neither can do by itself.
