### ISSUE TITLE
What are the main differences between magentic and declarai?

### ISSUE THREAD

**Issue by ogencoglu** [jackmpcollins/magentic#42]
A comparison to [declarai](https://declarai.com/) would be great in your documentation.

Similar to [what LMQL does with guidance etc.](https://docs.lmql.ai/en/latest/python/comparison.html)

**Comment by jackmpcollins** [comment]
Hi @ogencoglu , I am keeping the documentation here strictly about magentic - otherwise there are a lot of packages for which I would have to write comparisons. I'm happy to support declarai writing a comparison in their documentation by answering any questions you have. Thanks
