### ISSUE TITLE
Cannot specify max_tokens in OpenaiChatModel

### ISSUE THREAD

**Issue by tranhoangnguyen03** [jackmpcollins/magentic#44]
I'm using a Llama_cpp backend that imitates OpenAI's API. Its default max_tokens is set to 10 whereas OpenAI's default is set to None (I think). Without the ability to specify max_tokens, I cannot use Magentic with OSS LLMs :(

**Comment by jackmpcollins** [comment]
@tranhoangnguyen03 Thanks for reporting this! I've added this param now and released as https://github.com/jackmpcollins/magentic/releases/tag/v0.7.2  Please let me know if have any more issues.
