### ISSUE TITLE
Can this be used with Ollama?

### ISSUE THREAD

**Issue by carlosalvidrez** [jackmpcollins/magentic#50]
Wondering if you guys plan to allow this to work with local Ollama models.
Thanks!

**Comment by jackmpcollins** [comment]
Hi @carlosalvidrez, it should be possible to use `magentic` with ollama by using a proxy/adapter to make it compatible with the OpenAI API. See for example the instructions in PR https://github.com/jackmpcollins/magentic/pull/43 which use litellm. I have tried just now to get this working but I am getting errors from litellm. Please let me know if you get this working.

Also some relevant [notes from the README](https://github.com/jackmpcollins/magentic/tree/17e2c6137dcee192126b950d932188a60093f250#configuration)

> Since magentic uses the openai Python package, setting the OPENAI_API_BASE environment variable or openai.api_base in code allows you to use it with any OpenAI-compatible API e.g. [Azure OpenAI Service](https://learn.microsoft.com/en-us/azure/ai-services/openai/quickstart?tabs=command-line&pivots=programming-language-python#create-a-new-python-application), [LocalAI](https://localai.io/howtos/easy-request-openai/). Note that if the API does not support function calling then you will not be able to create prompt-functions that return Python objects, but other features of magentic will still work.

**Comment by jackmpcollins** [comment]
Hi @carlosalvidrez  I just released https://github.com/jackmpcollins/magentic/releases/tag/v0.9.0 which adds LiteLLM as a backend and allows you to use Ollama (and many other providers and LLMs) with magentic. The above note about magentic feature support is still relevant.

The following code should work for you after `pip install --upgrade magentic[litellm]` and assuming ollama is installed.

```python
from magentic import prompt
from magentic.chat_model.litellm_chat_model import LitellmChatModel


@prompt(
    "Talk to me! ",
    model=LitellmChatModel("ollama/llama2"),
)
def say_hello() -> str:
    ...


say_hello()
```

See the [Backend/LLM Configuration section of the README](https://github.com/jackmpcollins/magentic/tree/5b4b1012e630bd01baa0ef8bf3caf86fb68ae993#backendllm-configuration) for how to set the LiteLLM backend and Ollama as the default using environment variables.

**Comment by carlosalvidrez** [comment]
Will give it a shot, thank you!!

**Comment by knoopx** [comment]
llmlite is kind of meh, has the prompt hardcored in the library and basically only supports llama2...

**Comment by jackmpcollins** [comment]
> llmlite is kind of meh, has the prompt template hardcored in the library and basically only supports llama2...

@knoopx  Is there something that you haven't been able to do using magentic? For local models I think `LitellmChatModel` + ollama is one option, and `OpenaiChatModel` + openai-compatible API is another option. For example with llama.cpp https://github.com/abetlen/llama-cpp-python/blob/main/examples/notebooks/Functions.ipynb

I've very happy to look into a specific issue if you want to open a new github issue for it!
