### ISSUE TITLE
Temporary solution for AttributeError: module ‘openai’ has no attribute ‘ChatCompletion’

### ISSUE THREAD

**Issue by yudataguy** [jackmpcollins/magentic#57]
Due to the latest openai package update, you would likely encounter this error. 

Temp fix:
```
pip install "openai<1.0.0"
```

**Comment by jackmpcollins** [comment]
Thanks for reporting. I have set an upper bound on the openai version and release this as https://github.com/jackmpcollins/magentic/releases/tag/v0.9.1

I will update the package to use openai v1 shortly.
