### ISSUE TITLE
Support `gpt-4-vision-preview`

### ISSUE THREAD

**Issue by PaarthShah** [jackmpcollins/magentic#58]
https://platform.openai.com/docs/guides/vision

In my ideal scenario, there should be a clean way to accept a:
- [PIL.Image](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image)
- `bytes`
- an `https` URL

**Comment by jackmpcollins** [comment]
I agree. With the url case handled the other two should be easy as they are just conversion to the base64/data url.

I think finding the right API design for this could be tricky. Some observations
1. a `detail` parameter (low, high, auto) can be provided for each image
1. multiple images and text snippets can be provided at once / in a single user message

---

Supporting `detail` and other arguments for _each_ image requires associating these with each function parameter. Something like this would work

```python
from typing import Annotated
from magentic import prompt, ImageUrl

@prompt("What's in this image?")
def describe_image(image: Annotated[str, ImageUrl(detail="high")]) -> str:
    ...
```

Though it might be nice to simplify the case of passing no args. Here `ImageUrl` is just a type alias for `str`.

```python
from typing import Annotated
from magentic import prompt, ImageUrl, ImageUrlOptions

@prompt("What's in this image?")
def describe_image(image: ImageUrl) -> str:
    ...

@prompt("What's in this image?")
def describe_image(image: Annotated[ImageUrl, ImageUrlOptions(detail="high")]) -> str:
    ...
```

To handle `bytes` there could be a `ImageBytes` type alias for bytes.

---

Multiple text snippets and the ordering of text and images _could_ be defined in the single `@prompt` string, though this seems like the start of a template language to me so I'd rather avoid it. When a parameter is not mentioned in the prompt the default behavior would be to put the images after the text in the order they appear as parameters in the function.

```python
from magentic import prompt, ImageUrl

@prompt(
    """What changes between these images?
{image1}{image2}
Describe in lots of detail"""
)
def describe_image(image1: ImageUrl, image2: ImageUrl) -> str:
    ...
```

---

It seems like the best option for the moment is to implement just the `ImageUrl` and `ImageBytes` type aliases with `@prompt`, and simply add these to the message content after the prompt string. The more complex cases can be revisited later if/when there is demand for them.

So

```python
@prompt("What's in this image?")
def describe_image(image: ImageUrl) -> str:
    ...

describe_image("https://...")
```

becomes

```
	{
      "role": "user",
      "content": [
        {"type": "text", "text": "What’s in this image?"},
        {
          "type": "image_url",
          "image_url": {
            "url": "https://...",
          },
        },
      ],
    }
```

Please let me know what your thoughts are on this.

**Comment by jackmpcollins** [comment]
I'm not planning to add support for this for the moment. I'd recommend checking out https://www.askmarvin.ai/docs/images/generation/#generating-images-from-functions which has a similar API to what I outlined above.

**Comment by mnicstruwig** [comment]
@jackmpcollins I'm a bit confused by the API you linked, which, while lovely, is about _generating_ images, rather than a neat way of including an image so that we can query using the image as context using GPT-4-Vision.

Unless I'm misunderstanding something (which is possible!)

This suggestions you posted above:

```python
@prompt("What's in this image?")
def describe_image(image: ImageUrl) -> str:
    ...

describe_image("https://...")```

Makes the most sense for me, from the discussion.

**Comment by jackmpcollins** [comment]
@mnicstruwig  😅  You're right, sorry! Skimmed too fast.  Since it doesn't seem to exist elsewhere I'll try get to this in the next few weeks.

Are you currently using the OpenAI API directly for this? Are there any particular parameters/features you would need access to as part of this?

**Comment by jackmpcollins** [comment]
@mnicstruwig @PaarthShah  I have a prototype of this working in PR https://github.com/jackmpcollins/magentic/pull/116 . I ended up using `@chatprompt` instead of `prompt` as it allowed things to be more explicit and customizable. Please let me know your thoughts, and if/how you end up customizing things.

Release https://github.com/jackmpcollins/magentic/releases/tag/v0.15.0 enables more customizability of `Message` subclasses from outside of the `magentic` package itself. So using https://github.com/jackmpcollins/magentic/releases/tag/v0.15.0 in combination with the code in PR https://github.com/jackmpcollins/magentic/pull/116 copied to your own codebase will allow you to use GPT4 vision.

**Comment by jackmpcollins** [comment]
@mnicstruwig @PaarthShah  I've published release https://github.com/jackmpcollins/magentic/releases/tag/v0.17.0 containing `UserImageMessage` which can be used to send images to GPT4 Vision. See docs page for more info https://magentic.dev/vision/ . Let me know what you think and if this needs any updates, thanks.

**Comment by jackmpcollins** [comment]
The default model used by magentic is now `gpt-4-turbo` as of https://github.com/jackmpcollins/magentic/releases/tag/v0.20.0 which supports vision _and_ function calling 🚀  Some examples on the docs page https://magentic.dev/vision/
