### ISSUE TITLE
Azure OpenAI not working

### ISSUE THREAD

**Issue by kaaloo** [jackmpcollins/magentic#63]
Hi,

After some testing I realized that it's not possible to use `magentic` with Azure OpenAI.  The reason is that in the following line the `OpenAI` client is hard coded whereas an `AzureOpenAI` client would be required.  Same thing with the async versions of course.

https://github.com/jackmpcollins/magentic/blob/main/src/magentic/chat_model/openai_chat_model.py#L103

See the Azure OpenAI example in their repo:

https://github.com/openai/openai-python/blob/f6c2aedfe3dfceeabd551909b572d72c7cef4373/examples/azure.py

What would be the best way to support this in the code base?  There is a `OPENAI_API_TYPE` env var that could be checked to determine which client to use.  If `None` or `"openai"` keep the same behavior, if `"azure"` then use the Azure client. Is that too much of a hack?

Even better the `openai` module exposes an `api_type` constant that is type checked (I think).

https://github.com/openai/openai-python/blob/f6c2aedfe3dfceeabd551909b572d72c7cef4373/src/openai/__init__.py#L120

**Comment by piiq** [comment]
resolved by #65

**Comment by jackmpcollins** [comment]
Fix released now in https://github.com/jackmpcollins/magentic/releases/tag/v0.11.0
