### ISSUE TITLE
Add support to set openai base URL from magentic env variable

### ISSUE THREAD

**Issue by piiq** [jackmpcollins/magentic#66]
Hi 👋,

With the release of openai version 1.0, the OPENAI_API_BASE has been deprecated in favor of creating a client or similar constructs. This change is one of the reasons the Azure PR (https://github.com/jackmpcollins/magentic/pull/65) existed and this issue https://github.com/openai/openai-python/issues/745 is still open.

The beauty of Magnetic, for me, has always been its simplicity and brevity. It stands out against more complex tools like Langchain or even the vanilla OpenAI library. I can typically achieve what I need in just four lines of code: import prompt, write decorator, define function, and call function. This is in stark contrast to the 10s of lines required for setting up clients, defining abstractions, and other setup processes that are peripheral to my goals.

The use of environment variables is pretty convenient. I could set them once for a project and forget about them.

In this context I want to ask the following question:
Is there a way to incorporate the functionality that we had with OPENAI_API_BASE with this new solution?
It would be very convenient to be using openai compatible apis by simply switching a value in a configuration (.env) file

When using vanilla openai I can pass the base_url when instantiating the client

`openai.OpenAI(base_url="http://localhost:1234/v1")`

in magentic's `openai_chatcompletion_create` the client is generated with defaults
<img width="742" alt="image" src="https://github.com/jackmpcollins/magentic/assets/11668535/8c9ff8e4-4f4f-467e-ae8b-9455d9da74f9">

Would it be possible to do something like `OpenAI(**some_settings)` to specify the arguments that OpenAI accepts on init?

Anyway, Thank you for your time and this excellent library. I look forward to any possible solutions or guidance you can offer.

**Comment by jackmpcollins** [comment]
@piiq Thanks for reporting. Should be fixed now and released in https://github.com/jackmpcollins/magentic/releases/tag/v0.11.1 . This allows you to either set the `MAGENTIC_OPENAI_BASE_URL` env var, or set the `base_url` parameter in `OpenaiChatModel`. Let me know if there are any remaining issues with this

**Comment by piiq** [comment]
@jackmpcollins you dropped this
👑
