### ISSUE TITLE
Is tqdm used in the project?

### ISSUE THREAD

**Issue by Lawouach** [jackmpcollins/magentic#69]
Hi,

I see tqdm is a required dependency. Is that a necessary one though? I'm trying to keep my dependency tree as lean as I can.

Thanks,

**Comment by jackmpcollins** [comment]
Hi @Lawouach , tqdm is not required by magentic directly. See
https://github.com/jackmpcollins/magentic/blob/1195a1a6b240f38fa0d7ad457f5463c64d37435b/pyproject.toml#L27-L33

It is however a transitive dependency from openai, so you will have to take this up with them! https://github.com/openai/openai-python/blob/17ac6779958b2b74999c634c4ea4c7b74906027a/pyproject.toml#L10-L18
